---
# Used for paper results
plot_sequences: true # optional to plot all 5+ frame sequences on wandb
save_plots_locally: false # optional to save plots on local machine
visualisation_channels: ${channels.visualisation_channels}
with_colormaps: true
mask_out_clouds: true

detection_methods:
  # Table 1 ~ basic

  - method: "src.evaluation.methods.CosPixels" # Cosine baseline, mem 1
    method_args:
      tile_size: [32, 32]
      overlap: ${dataset.test_overlap}

  - method: "src.evaluation.methods.DiffPixels" # RMSE baseline, mem 1
    method_args:
      tile_size: [32, 32]
      overlap: ${dataset.test_overlap}

  - method: "src.evaluation.methods.CosEmbeddingImage" # Cosine embedding, mem 1
    method_args: 
      tile_size: ${dataset.window_size}
      overlap: ${dataset.test_overlap}

  - method: "src.evaluation.methods.DiffEmbeddingImage" # RMSE embedding, mem 1
    method_args: 
      tile_size: ${dataset.window_size}
      overlap: ${dataset.test_overlap}
        
  - method: "src.evaluation.methods.KLDivEmbeddingImage" # KL-div (mem 1)
    method_args: 
      tile_size: ${dataset.window_size}
      overlap: ${dataset.test_overlap}
    
  - method: "src.evaluation.methods.WasserEmbeddingImage" # Wasserstein (mem 1)
    method_args: 
      tile_size: ${dataset.window_size}
      overlap: ${dataset.test_overlap}

  # Table 2 ~ with memory

  - method: "src.evaluation.methods.CosPixels" # Cosine baseline, mem 3
    method_args:
      memory_size: 3
      tile_size: [32, 32]
      overlap: ${dataset.test_overlap}
  - method: "src.evaluation.methods.CosEmbeddingImage" # Cosine embedding, mem 3
    method_args: 
      memory_size: 3
      tile_size: ${dataset.window_size}
      overlap: ${dataset.test_overlap}



    
summary_stat_methods:

  - method: "src.evaluation.methods.AreaUnderPrecisionRecall"
    method_args: {}
    
  - method: "src.evaluation.methods.PrecisionAt100Recall"
    method_args: {}
    
    