---
train:
        transformer_cls: 'src.data.transformations.NoTransformer'

        transform_list: []

test:
        transformer_cls: 'src.data.transformations.NoTransformer'

        transform_list: []
