---
# FL setup
fraction_fit: 0.0001
fraction_eval: 0.001
min_fit_clients: 10
min_eval_clients: 30
local_epochs: 10
num_rounds: 10
num_clients: 100
config_fit:
  lr: 0.001
  momentum: 0.9
  local_epochs: 10

# RaVAEn settings
name: "VAE_128small"
dataset: alpha_multiscene_tiny
training: simple_vae
module: deeper_vae
normalisation: log_scale
channels: high_res

log_dir: "/home/lucap/l46/l46-project/FedRaVAEn-master/outputs/results"
cache_dir: "/home/lucap/l46/l46-project/FedRaVAEn-master/outputs/cache"
