---
entity: "mlpayloads"

# FL setup
fraction_fit: 0.0001
fraction_eval: 0.001
min_fit_clients: 20
min_eval_clients: 20
local_epochs: 10
num_rounds: 5
num_clients: 20
config_fit:
  lr: 0.001
  momentum: 0.9
  local_epochs: 10


# RaVAEn setup
log_dir: "/home/lucap/l46/l46-project/RaVAEn-master/outputs/results"
cache_dir: "/home/lucap/l46/l46-project/RaVAEn-master/outputs/cache"
