---
class: src.models.module.Module

model_class: 'src.models.ae_vae_models.deeper_ae.DeeperAE'

model_cls_args:
  hidden_channels: [64, 128, 256] # number of channels after each downscale. Reversed on upscale
  latent_dim: 1024                # bottleneck size
  extra_depth_on_scale: 2        # after each downscale and upscale, this many convolutions are applied
  visualisation_channels: ${channels.visualisation_channels}
