---
# location in bucket: validation/validation_data_final/floods
data_module_name: "floods_evaluation"

# Root directory for train, val and test data, nested in folders inside this location
root_folder: "/data/local/validation_data_final/floods"

window_size: [32, 32]
overlap: [0, 0]
input_shape : [32, 32] # used in evaluate_model.py to get cfg_module['input_shape']


train:
  folder_filter:
    - "I::1"

  dataset_cls: 'src.data.dataset.LocationDataset'
  dataset_cls_args:
    tiling_strategy_cls: 'src.data.tiling_strategy.TilingStrategyFullGrid'
    tiling_strategy_args:
      window_size: ${dataset.window_size}
      overlap: ${dataset.overlap}$

    dataset_specs:
      - src.data.dataset.SingleFolderImageDataset:
          folder_path: 'S2'

          normaliser_cls: ${normalisation.normaliser_cls}
          normaliser_args: ${normalisation.normaliser_args}

          channels: ${channels.channels}

  shuffle: true

  batch_size: ${training.batch_size_train}
  num_workers: ${training.num_workers}

valid:
  folder_filter:
    - "I::1"

  dataset_cls: 'src.data.dataset.LocationDataset'
  dataset_cls_args:
    tiling_strategy_cls: 'src.data.tiling_strategy.TilingStrategyFullGrid'
    tiling_strategy_args:
      window_size: ${dataset.window_size}
      overlap: ${dataset.overlap}$

    dataset_specs:
      - src.data.dataset.SingleFolderImageDataset:
          folder_path: 'S2'

          normaliser_cls: ${normalisation.normaliser_cls}
          normaliser_args: ${normalisation.normaliser_args}
          filter_cls: 'src.data.filters.SliceFilter'
          filter_args:
            f_slice: ':2'

          channels: ${channels.channels}

  batch_size: ${training.batch_size_valid}
  num_workers: ${training.num_workers}

test:
  folder_filter:
    - "I::"

  dataset_cls: 'src.data.dataset.LocationDataset'
  dataset_cls_args:
    tiling_strategy_cls: 'src.data.tiling_strategy.TilingStrategyFullGrid'
    tiling_strategy_args:
      window_size: ${dataset.window_size}
      overlap: ${dataset.overlap}$

    dataset_specs:
      - src.data.dataset.SingleFolderImageDataset:
          folder_path: 'S2'
          normaliser_cls: ${normalisation.normaliser_cls}
          normaliser_args: ${normalisation.normaliser_args}

          channels: ${channels.channels}

      - src.data.dataset.SingleFolderChangeDataset:
          folder_path: 'changes'
          folder_path_s2: 'S2'

  batch_size: ${training.batch_size_test}
  num_workers: ${training.num_workers}

  keep_separate: true
