---
# Possible channels for worldfloods data are:
#     ['B1','B2','B3','B4','B5','B6','B7','B8','B8A','B9','B10','B11','B12','QA60','probability']
channels: ['B1','B2','B3','B4','B5','B6','B7','B8','B8A','B9','B10','B11','B12']

visualisation_channels: [3, 2, 1]
